name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  lfs: true
            - uses: actions-rs/toolchain@v1
            - run: choco install dotnet netfx-4.8 python3 wixtoolset
            - run: cargo install cargo-wix
            - env:
                  SSL_COM_USERNAME: ${{ github.event_name == 'release' && secrets.SSL_COM_USERNAME || '' }}
                  SSL_COM_PASSWORD: ${{ github.event_name == 'release' && secrets.SSL_COM_PASSWORD || '' }}
                  SSL_COM_CREDENTIAL_ID: ${{ github.event_name == 'release' && secrets.SSL_COM_CREDENTIAL_ID || '' }}
                  SSL_COM_TOTP_SECRET: ${{ github.event_name == 'release' && secrets.SSL_COM_TOTP_SECRET || '' }}
                  SIGN: ${{ github.event_name == 'release' && '--sign' || '' }}
              run: python build.py %SIGN%
            - uses: actions/upload-artifact@v2
              with:
                  name: thelio-io
                  path: target/wix/thelio-io-*.msi
